---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: "Include mattslab.plex_suite"
      include_role:
        name: "mattslab.plex_suite"
