---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-debian11-ansible:latest}"
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup/:/sys/fs/cgroup:rw
    cgroupns_mode: host
    priveleged: true
provisioner:
  name: ansible
  env:
    PY_COLORS: '1'
    ANSIBLE_FORCE_COLOR: '1'
verifier:
  name: ansible
